### ISSUE TITLE
Question regarding EmpPdf

### ISSUE THREAD

**Issue by dsjoerg** [strohel/PyBayes#12]
Hello, please forgive this somewhat noobish question.

I am hoping to use this library for some particle filtering.  However the p_yt_xt cpdf that I would like to supply is an _empirical_ cpdf.  That is, x_t can take on various discrete values, and each value of x_t has its own pdf for y_t.

Trivial example,
```
low = pb.pdfs.EmpPdf(np.array([[0.],[1.]], ndmin=2))
high = pb.pdfs.EmpPdf(np.array([[0.],[1.],[1.],[1.]], ndmin=2))
```
Now we'd like to construct a cpdf which, when x_t = 0, y_t follows the low pdf and when x_t = 1 it follows the high pdf.
To do this, I could try to make a subclass of EmpPdf called ConditionalEmpPdf, but maybe I'm misunderstanding something about the code base and this functionality is already provided or is composable from existing classes.

Also I can't tell from the code if it is set up to correctly handle discrete probability functions like this.

Thanks in advance!  —David

**Comment by dsjoerg** [comment]
Hmm, perhaps I have answered my own question.  If I'm reading this right, ParticleFilter does not currently support using an EmpPdf as the p_yt_xt, because it calls ```eval_log``` on the p_yt_xt, but EmpPdf does not implement ```eval_log```.   Which would mean that discrete probability functions are not yet supported.
If I'm missing something I'd be grateful to be corrected.  Thank you,  —David

**Comment by strohel** [comment]
Hi David,
little time, so I'll answer briefly:

Regarding ConditionalEmpPdf - it is not directly composable out of existing classes, but should be super-easy to implement, just hold 2 Pdf implementations and call the same method od the chosen one depending on the condition.

Regarding ParticleFilte and EmpPdf as p_yt_xt - yes, currently EmpPdf cannot serve as it, but if you could implement its meaningful eval_log() funciton, it should work. If it is generic enough, please send it to me as a pull request and we'll see.

**Comment by dsjoerg** [comment]
Makes sense, thank you!
