### ISSUE TITLE
Relicense under BSD

### ISSUE THREAD

**Issue by twiecki** [strohel/PyBayes#7]
I think there are many good reasons to not go with GPL these days. Mainly it prevents other OSS developers using more liberal licenses like MIT, BSD or Apache from using your code.

**Comment by hyandell** [comment]
Not sure if this is an active project, but I noticed the above and went ahead and made the changes for PyBayes to be under BSD :)

**Comment by twiecki** [comment]
:+1: ;)

**Comment by strohel** [comment]
Thanks, @hyandell. I'll have a look at it, if time permits. (sorry for being extremely slow responsive, you know...)
